name: Build and Deploy to Azure App Service

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment where to deploy."
        type: string
        default: sanbox
      branch:
        description: "Which branch we want to deploy (default: main)."
        type: string
        default: main

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    uses: toninoes/modulodromo/.github/workflows/deploy-docker-web-app.yml@main
    with:
      environment: sandbox
    secrets: inherit